// SPDX-License-Identifier: GPL-3.0-or-later
//! Single-source keyboard shortcut table.
//!
//! Every shortcut in the app is registered from [`SHORTCUTS`], rendered into
//! the `?` overlay from [`SHORTCUTS`], and documented by `--dump-shortcuts`
//! from [`SHORTCUTS`]. Add a row here and all three follow; the snapshot
//! test fails on drift.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Action {
    Down,
    Up,
    First,
    Last,
    PageDown,
    PageUp,
    Search,
    Launch,
    Play,
    Add,
    Update,
    Remove,
    Favorite,
    Hide,
    Settings,
    Help,
    Clear,
}

#[derive(Debug, Clone, Copy)]
pub struct Shortcut {
    pub action: Action,
    /// GTK accelerator string, e.g. `"j"`, `"slash"`, `"Return"`.
    pub keys: &'static str,
    pub description: &'static str,
}

pub const SHORTCUTS: &[Shortcut] = &[
    Shortcut {
        action: Action::Down,
        keys: "j",
        description: "Move selection down",
    },
    Shortcut {
        action: Action::Down,
        keys: "Down",
        description: "Move selection down",
    },
    Shortcut {
        action: Action::Up,
        keys: "k",
        description: "Move selection up",
    },
    Shortcut {
        action: Action::Up,
        keys: "Up",
        description: "Move selection up",
    },
    Shortcut {
        action: Action::First,
        keys: "Home",
        description: "Jump to first",
    },
    Shortcut {
        action: Action::Last,
        keys: "End",
        description: "Jump to last",
    },
    Shortcut {
        action: Action::PageDown,
        keys: "Page_Down",
        description: "Move down a page",
    },
    Shortcut {
        action: Action::PageUp,
        keys: "Page_Up",
        description: "Move up a page",
    },
    Shortcut {
        action: Action::Search,
        keys: "slash",
        description: "Focus search",
    },
    Shortcut {
        action: Action::Launch,
        keys: "Return",
        description: "Launch selected AppImage",
    },
    Shortcut {
        action: Action::Play,
        keys: "p",
        description: "Play selected AppImage",
    },
    Shortcut {
        action: Action::Add,
        keys: "a",
        description: "Add AppImage",
    },
    Shortcut {
        action: Action::Update,
        keys: "u",
        description: "Update selected AppImage",
    },
    Shortcut {
        action: Action::Remove,
        keys: "x",
        description: "Remove selected AppImage",
    },
    Shortcut {
        action: Action::Remove,
        keys: "Delete",
        description: "Remove selected AppImage",
    },
    Shortcut {
        action: Action::Favorite,
        keys: "f",
        description: "Toggle favorite",
    },
    Shortcut {
        action: Action::Hide,
        keys: "h",
        description: "Hide selected AppImage",
    },
    Shortcut {
        action: Action::Settings,
        keys: "s",
        description: "Open settings",
    },
    Shortcut {
        action: Action::Help,
        keys: "question",
        description: "Show shortcuts",
    },
    Shortcut {
        action: Action::Clear,
        keys: "Escape",
        description: "Clear search / back",
    },
];

/// Render the table as Markdown (used by `--dump-shortcuts` and docs).
pub fn dump_markdown() -> String {
    let mut out = String::from("# Omalaunch keyboard shortcuts\n\n");
    out.push_str("<!-- GENERATED by `omalaunch --dump-shortcuts`. Do not hand-edit. -->\n\n");
    out.push_str("| Keys | Action |\n| --- | --- |\n");
    for row in SHORTCUTS {
        out.push_str(&format!("| `{}` | {} |\n", row.keys, row.description));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn table_matches_committed_snapshot() {
        let fixture = include_str!("../tests/fixtures/shortcuts.md");
        assert_eq!(
            dump_markdown(),
            fixture,
            "run `omalaunch --dump-shortcuts` to refresh"
        );
    }

    #[test]
    fn every_action_has_at_least_one_binding() {
        let mut seen = HashSet::new();
        for row in SHORTCUTS {
            seen.insert(row.action);
        }
        for action in [
            Action::Down,
            Action::Up,
            Action::First,
            Action::Last,
            Action::PageDown,
            Action::PageUp,
            Action::Search,
            Action::Launch,
            Action::Play,
            Action::Add,
            Action::Update,
            Action::Remove,
            Action::Favorite,
            Action::Hide,
            Action::Settings,
            Action::Help,
            Action::Clear,
        ] {
            assert!(seen.contains(&action), "unbound action: {action:?}");
        }
    }

    #[test]
    fn no_duplicate_bindings() {
        let mut seen = HashSet::new();
        for row in SHORTCUTS {
            assert!(seen.insert(row.keys), "duplicate binding: {}", row.keys);
        }
    }
}
